### PR TITLE
FEATURE: TMA-221 Ruby SDK supports URN for date dimension

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/32/ : SUCCESS in 17s

**Comment by panjan** [comment]
What do you think @Teknikov?

**Comment by panjan** [comment]
@vhtien

**Comment by vhtien** [comment]
updated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-opensource-repository-check/2/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/35/ : SUCCESS in 15s

**Pull request merged**
