### PR TITLE
FEATURE: TMA-244 Document the ADD methods

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/18/ : SUCCESS in 6s

**Comment by vhtien** [comment]
should be merged after https://github.com/gooddata/gooddata-ruby/pull/751

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/19/ : SUCCESS in 6s

**Comment by Teknikov** [comment]
I've checked the doc and returned to Tien to commit when agreed.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/21/ : SUCCESS in 7s

**Pull request merged**
