### PR TITLE
Add Rake task spelling:check

### PR DESCRIPTION
**Pull request by panjan**
Added a rake task for automated spell-checking. We can plug it into our CI build.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/17/ : SUCCESS in 7s

**Comment by korczis** [comment]
Can you remove .aspell.en.pws pls?

**Comment by korczis** [comment]
Or what is it for?

**Comment by panjan** [comment]
It is a list of known words. Without it, the task would fail.

**Comment by panjan** [comment]
But we can rename it to something more descriptive.

**Comment by korczis** [comment]
Lets discuss this personaly at Monday.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/20/ : SUCCESS in 7s

**Pull request merged**
