### PR TITLE
Cookbook cleanup

### PR DESCRIPTION
**Pull request by zsvoboda**
I have cleaned up the base documentation and fixed typos / errors.

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-examples-pull-request-builder/22/

**Comment by korczis** [comment]
Ok to merge.

**Pull request merged**
