### PR TITLE
TMA-219 MAQL Diff API support in Ruby SDK

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/33/ : SUCCESS in 20s

**Comment by panjan** [comment]
@Teknikov

**Comment by panjan** [comment]
@vhtien

**Comment by vhtien** [comment]
updated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-examples-opensource-repository-check/1/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-examples-tests-zuul/34/ : SUCCESS in 17s

**Pull request merged**
